import pandas as pd
df = pd.read_csv("titanic.csv")
print("First 5 rows of the Titanic dataset:")
print(df.head(5))
print("\nLast 5 rows of the Titanic dataset:")
print(df.tail(5))
print("\nShape of Our Datase")
print(df.shape)
print("\n Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement")
print(df.info())
print("\nStatistics About The Dataframe")
print(df.describe())
print("\nChecking for Missing Values In The Dataset")
print(df.isnull().sum())
print("\nDroping Unnecessary Columns")
df.drop(columns = ["Cabin","Embarked"], axis=1, inplace=True)
print(df.head())
print("\nFilling Missing Values In 'Age' Column With 0")
df["Age"] = df["Age"].fillna(0)
print(df["Age"])
print(df["Age"].isnull().sum())
df = pd.concat([df,pd.get_dummies(df["Sex"])], axis=1)
print("\nAfter Encoding")
print(df)
survived = (df["Survived"]==1).sum()
print("\nTotal Number of Survivors in the Dataset:")
print(survived)
Not_survived = (df["Survived"]==0).sum()
print("\nTotal Number of Non Survivors in the Dataset:")
print(Not_survived)
first_class = (df["Pclass"]==1).sum()
print("\nTotal Number of First Class Passengers:")
print(first_class)
second_class = (df["Pclass"]==2).sum()
print("\nTotal Number of Second Class Passengers:")
print(second_class)
third_class = (df["Pclass"]==3).sum()
print("\nTotal Number of Third Class Passengers:")
print(third_class)
category = df["Sex"].value_counts()
print("\nNumber of Male and Female Passengers:")    
print(category)
Survival_rate = df.groupby("Pclass")["Survived"].mean()
print("\nSurvival Rate Based On Passenger Class:")
print(Survival_rate)
df["family"] = df["SibSp"] + df["Parch"]
print("\nNumber of family members:")
print(df)
df["fare_per_person"] = df["Fare"]/(df["family"] + 1)
print("\nFare Per Person:")
print(df)
